<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('products')->insert([
            [
                'sku' => 'SKU-IPH15-128-BLK',
                'name' => 'Apple iPhone 15 128GB Black',
                'category' => 'Smartphone',
                'brand' => 'Apple',
                'tags' => json_encode(['มือถือ', '5G', 'เรือธง', 'iOS', 'กล้องคม'], JSON_UNESCAPED_UNICODE),
                'summary' => 'จอ OLED 6.1 นิ้ว รองรับ 5G กล้องหลัก 48MP เหมาะใช้งานทั่วไปและสายคอนเทนต์',
                'description' => 'Apple iPhone 15 128GB สีดำ หน้าจอ Super Retina XDR OLED 6.1 นิ้ว รองรับ HDR ชิปประมวลผลรุ่นใหม่ กล้องหลัก 48MP เหมาะกับผู้ที่ต้องการความเร็ว ความลื่นไหล และคุณภาพกล้องในเครื่องเดียว',
                'price' => 32900,
                'compare_price' => 35900,
                'cost' => 28000,
                'stock_qty' => 50,
                'cover_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvm6vJiItGwCtIb-Ujt9LrbFZZ3UMQ3WHk0g&s',
                'images' => json_encode([
                    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwC8_G0XfZorqlBAtxEjK9T4hUxmnCaL6oxw&s',
                    'https://www.jib.co.th/img_master/product/original/2023092117104862451_1.jpg',
                    'https://spiritpc.com/service/images/productimg/500/500/e206bb73-d803-4f0a-b500-06bb236c2914.png?own=true',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => $now,
                'notes' => 'สินค้าขายดี เหมาะสำหรับโปรโมชันหน้าแรก',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-S24-256-GRY',
                'name' => 'Samsung Galaxy S24 256GB Gray',
                'category' => 'Smartphone',
                'brand' => 'Samsung',
                'tags' => json_encode(['android', '5G', 'amoled', '120hz', 'ai'], JSON_UNESCAPED_UNICODE),
                'summary' => 'จอ AMOLED 120Hz พร้อมฟีเจอร์ AI ช่วยถ่ายภาพและใช้งานฉลาดขึ้น',
                'description' => 'Galaxy S24 256GB สีเทา หน้าจอ Dynamic AMOLED 2X 120Hz กล้องหลัก 50MP พร้อม AI ช่วยให้ภาพกลางคืนและภาพบุคคลดูดี รองรับ 5G เหมาะกับผู้ที่ต้องการมือถือประสิทธิภาพสูงและความยืดหยุ่นของ Android',
                'price' => 28900,
                'compare_price' => 31900,
                'cost' => 24000,
                'stock_qty' => 30,
                'cover_image' => '/images/products/galaxy_s24_gray_main.jpg',
                'images' => json_encode([
                    '/images/products/galaxy_s24_gray_1.jpg',
                    '/images/products/galaxy_s24_gray_2.jpg',
                    '/images/products/galaxy_s24_gray_3.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => $now,
                'notes' => 'เหมาะทำสินค้าขายร่วมกับอุปกรณ์เสริม',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-IPAD-AIR5-64-BLU',
                'name' => 'Apple iPad Air 5 64GB Blue',
                'category' => 'Tablet',
                'brand' => 'Apple',
                'tags' => json_encode(['tablet', 'apple', 'เรียน', 'ทำงาน', 'พกพา'], JSON_UNESCAPED_UNICODE),
                'summary' => 'แท็บเล็ตจอ 10.9 นิ้ว น้ำหนักเบา เหมาะเรียน ทำงาน จดโน้ต',
                'description' => 'iPad Air 5 64GB สีฟ้า เหมาะสำหรับเรียนและงานเอกสาร หน้าจอ 10.9 นิ้ว รองรับการจดโน้ต วาดรูป และทำงานหลายอย่างพร้อมกัน ใช้คู่คีย์บอร์ด/ปากกาได้ดี',
                'price' => 21900,
                'compare_price' => 23900,
                'cost' => 18000,
                'stock_qty' => 18,
                'cover_image' => '/images/products/ipad_air5_blue_main.jpg',
                'images' => json_encode([
                    '/images/products/ipad_air5_blue_1.jpg',
                    '/images/products/ipad_air5_blue_2.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => $now,
                'notes' => 'จัดเป็น bundle คู่ Apple Pencil ได้',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-SONY-WH1000XM5-BLK',
                'name' => 'Sony WH-1000XM5 Noise Cancelling Headphones Black',
                'category' => 'Audio',
                'brand' => 'Sony',
                'tags' => json_encode(['headphone', 'noise cancelling', 'bluetooth', 'พรีเมียม'], JSON_UNESCAPED_UNICODE),
                'summary' => 'หูฟังครอบหูตัดเสียงรบกวนระดับพรีเมียม เหมาะทำงานและเดินทาง',
                'description' => 'WH-1000XM5 เด่นเรื่องตัดเสียงรบกวน คุณภาพเสียงบาลานซ์ ใช้งานได้นาน เหมาะโฟกัสทำงาน/เดินทาง รองรับ Bluetooth ใช้ได้กับหลายอุปกรณ์',
                'price' => 12900,
                'compare_price' => 13900,
                'cost' => 9500,
                'stock_qty' => 22,
                'cover_image' => '/images/products/sony_wh1000xm5_black_main.jpg',
                'images' => json_encode([
                    '/images/products/sony_wh1000xm5_black_1.jpg',
                    '/images/products/sony_wh1000xm5_black_2.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => $now,
                'notes' => 'เหมาะเป็นสินค้าชูโรงหมวด Audio',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-DELL-XPS13-I7-16-512',
                'name' => 'Dell XPS 13 13.4" Intel Core i7 RAM 16GB SSD 512GB',
                'category' => 'Laptop',
                'brand' => 'Dell',
                'tags' => json_encode(['laptop', 'ultrabook', 'work', 'business'], JSON_UNESCAPED_UNICODE),
                'summary' => 'โน้ตบุ๊กบางเบา จอขอบบาง เหมาะทำงานเอกสาร ประชุมออนไลน์ และพกพา',
                'description' => 'Dell XPS 13 ดีไซน์พรีเมียม บางเบา จอ InfinityEdge ใช้ i7 + RAM 16GB + SSD 512GB เปิดโปรแกรมและไฟล์เร็ว เหมาะงานเอกสาร พรีเซนต์ และงานทั่วไปที่ต้องพกพา',
                'price' => 45900,
                'compare_price' => 48900,
                'cost' => 40000,
                'stock_qty' => 12,
                'cover_image' => '/images/products/dell_xps13_main.jpg',
                'images' => json_encode([
                    '/images/products/dell_xps13_1.jpg',
                    '/images/products/dell_xps13_2.jpg',
                    '/images/products/dell_xps13_3.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => $now,
                'notes' => 'เหมาะทำโปรโมชันร่วม Office หรืออุปกรณ์เสริม',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-LOGI-MXMASTER-3S',
                'name' => 'Logitech MX Master 3S Wireless Mouse Graphite',
                'category' => 'Accessory',
                'brand' => 'Logitech',
                'tags' => json_encode(['mouse', 'wireless', 'work', 'productivity'], JSON_UNESCAPED_UNICODE),
                'summary' => 'เมาส์ไร้สายสำหรับงานโปร จับถนัด เลื่อนนุ่ม ใช้งานได้หลายอุปกรณ์',
                'description' => 'MX Master 3S เหมาะงานเอกสาร/ออกแบบ/งานทั่วไปที่ต้องการความแม่นยำ รองรับหลายอุปกรณ์ สลับการเชื่อมต่อได้ ใช้งานได้นานต่อการชาร์จ',
                'price' => 3990,
                'compare_price' => 4290,
                'cost' => 2800,
                'stock_qty' => 45,
                'cover_image' => '/images/products/logitech_mxmaster3s_main.jpg',
                'images' => json_encode([
                    '/images/products/logitech_mxmaster3s_1.jpg',
                    '/images/products/logitech_mxmaster3s_2.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => $now,
                'notes' => 'ขายร่วมกับโน้ตบุ๊กและคีย์บอร์ดได้ดี',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-RAZER-BW-V4',
                'name' => 'Razer BlackWidow V4 Mechanical Keyboard RGB',
                'category' => 'Accessory',
                'brand' => 'Razer',
                'tags' => json_encode(['keyboard', 'gaming', 'mechanical', 'rgb'], JSON_UNESCAPED_UNICODE),
                'summary' => 'คีย์บอร์ด Mechanical ไฟ RGB เหมาะเล่นเกมและพิมพ์งาน ฟีลกดชัด',
                'description' => 'BlackWidow V4 โครงสร้างแข็งแรง ฟีลกดชัด เหมาะเล่นเกมและพิมพ์งานยาว ๆ มีไฟ RGB ปรับแต่งได้ รองรับการตั้งค่ามาโครเพิ่มความเร็วในการทำงาน',
                'price' => 5990,
                'compare_price' => 6490,
                'cost' => 4200,
                'stock_qty' => 28,
                'cover_image' => '/images/products/razer_blackwidow_v4_main.jpg',
                'images' => json_encode([
                    '/images/products/razer_blackwidow_v4_1.jpg',
                    '/images/products/razer_blackwidow_v4_2.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => $now,
                'notes' => 'แนะนำจัดชุดคู่เมาส์เกมมิ่ง',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-LG-OLED-55C',
                'name' => 'LG OLED TV 55" 4K Smart TV (WebOS)',
                'category' => 'TV',
                'brand' => 'LG',
                'tags' => json_encode(['tv', 'oled', '4k', 'smart tv', 'cinema'], JSON_UNESCAPED_UNICODE),
                'summary' => 'ทีวี OLED 55 นิ้ว 4K สีดำลึก คอนทราสต์สูง เหมาะดูหนังและเล่นเกม',
                'description' => 'LG OLED 55 นิ้ว 4K เด่นเรื่องสีดำลึกและคอนทราสต์สูง ระบบ WebOS ใช้งานแอปสตรีมมิ่งสะดวก เหมาะห้องนั่งเล่น/ห้องดูหนัง รองรับเชื่อมต่ออุปกรณ์หลากหลาย',
                'price' => 39900,
                'compare_price' => 42900,
                'cost' => 33000,
                'stock_qty' => 6,
                'cover_image' => '/images/products/lg_oled_55_main.jpg',
                'images' => json_encode([
                    '/images/products/lg_oled_55_1.jpg',
                    '/images/products/lg_oled_55_2.jpg',
                    '/images/products/lg_oled_55_3.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => $now,
                'notes' => 'เหมาะทำโปรร่วมซาวด์บาร์',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-SONY-A7IV-BODY',
                'name' => 'Sony A7 IV Mirrorless Camera Body',
                'category' => 'Camera',
                'brand' => 'Sony',
                'tags' => json_encode(['camera', 'mirrorless', 'full frame', 'creator', '4k'], JSON_UNESCAPED_UNICODE),
                'summary' => 'กล้อง Mirrorless Full Frame เหมาะถ่ายภาพนิ่งและวิดีโอสำหรับงานครีเอเตอร์',
                'description' => 'Sony A7 IV สมดุลภาพนิ่งและวิดีโอ เซนเซอร์ Full Frame รายละเอียดสูง โฟกัสไว เหมาะถ่ายบุคคล สินค้า อีเวนต์ และงานคอนเทนต์ มีเลนส์/อุปกรณ์เสริมหลากหลาย',
                'price' => 79900,
                'compare_price' => 82900,
                'cost' => 70000,
                'stock_qty' => 7,
                'cover_image' => '/images/products/sony_a7iv_main.jpg',
                'images' => json_encode([
                    '/images/products/sony_a7iv_1.jpg',
                    '/images/products/sony_a7iv_2.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => $now,
                'notes' => 'แนะนำทำ bundle คู่เลนส์ยอดนิยม',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'sku' => 'SKU-SSD-SAM-980PRO-1TB',
                'name' => 'Samsung 980 PRO NVMe SSD 1TB PCIe Gen4',
                'category' => 'Storage',
                'brand' => 'Samsung',
                'tags' => json_encode(['ssd', 'nvme', 'pcie gen4', 'upgrade', 'gaming'], JSON_UNESCAPED_UNICODE),
                'summary' => 'SSD NVMe ความเร็วสูง เหมาะอัปเกรดพีซี/โน้ตบุ๊ก ลดเวลาโหลดเกมและไฟล์ใหญ่',
                'description' => 'Samsung 980 PRO 1TB รองรับ PCIe Gen4 ความเร็วอ่าน/เขียนสูง เหมาะอัปเกรดเครื่องเพื่อเพิ่มความลื่นไหล เปิดโปรแกรม/โหลดเกมเร็ว และทำงานไฟล์ใหญ่ เช่น ตัดต่อวิดีโอ',
                'price' => 4590,
                'compare_price' => 4990,
                'cost' => 3200,
                'stock_qty' => 60,
                'cover_image' => '/images/products/samsung_980pro_1tb_main.jpg',
                'images' => json_encode([
                    '/images/products/samsung_980pro_1tb_1.jpg',
                    '/images/products/samsung_980pro_1tb_2.jpg',
                ], JSON_UNESCAPED_UNICODE),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => $now,
                'notes' => 'เหมาะทำโปรร่วมกับเมนบอร์ด/โน้ตบุ๊ก',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}