<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            // 1
            [
                'sku' => 'SKU-IPH15-128-BLK',
                'barcode' => '8851000000011',
                'name' => 'Apple iPhone 15 128GB Black',
                'slug' => Str::slug('Apple iPhone 15 128GB Black'),
                'short_description' => 'สมาร์ทโฟนหน้าจอ OLED ขนาด 6.1 นิ้ว รองรับ 5G กล้องหลัก 48MP พร้อมการประมวลผลภาพระดับสูง เหมาะทั้งใช้งานทั่วไปและสายคอนเทนต์',
                'description' => 'Apple iPhone 15 รุ่นความจุ 128GB สีดำ มาพร้อมหน้าจอ Super Retina XDR OLED ขนาด 6.1 นิ้ว ให้สีสันคมชัดและความสว่างสูง รองรับ HDR เหมาะสำหรับรับชมวิดีโอและเล่นเกม ชิปประมวลผลรุ่นใหม่ให้ประสิทธิภาพรวดเร็ว การจัดการพลังงานดีขึ้น กล้องหลัก 48MP ช่วยให้ภาพคมและเก็บรายละเอียดได้ดี รองรับการถ่ายวิดีโอความละเอียดสูง เหมาะสำหรับผู้ต้องการโทรศัพท์ที่บาลานซ์ทั้งความเร็ว คุณภาพกล้อง และความลื่นไหลของระบบ',
                'category_name' => 'Smartphone',
                'brand_name' => 'Apple',
                'tags' => json_encode(['มือถือ', '5G', 'เรือธง', 'iOS', 'กล้องคม']),
                'price' => 32900,
                'compare_at_price' => 35900,
                'cost' => 28000,
                'tax_rate' => 7.00,
                'discount_type' => 'percent',
                'discount_value' => 10,
                'stock_qty' => 50,
                'reserved_qty' => 5,
                'reorder_point' => 10,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.172,
                'length_cm' => 14.76,
                'width_cm' => 7.15,
                'height_cm' => 0.78,
                'shipping_class' => 'standard',
                'cover_image_url' => '/images/products/iphone15_black_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/iphone15_black_1.jpg',
                    '/images/products/iphone15_black_2.jpg',
                    '/images/products/iphone15_black_3.jpg',
                ]),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => now(),
                'meta_title' => 'Apple iPhone 15 128GB Black | ของแท้ประกันศูนย์',
                'meta_description' => 'iPhone 15 128GB สีดำ หน้าจอ OLED กล้อง 48MP รองรับ 5G พร้อมจัดส่งทั่วประเทศ',
                'meta_keywords' => 'iphone 15, apple, ios, smartphone, 5g',
                'notes' => 'สินค้าขายดี เหมาะสำหรับโปรโมชันหน้าแรก',
                'attributes' => json_encode([
                    'color' => 'Black',
                    'storage' => '128GB',
                    'display' => '6.1-inch OLED',
                    'camera' => '48MP main',
                    'connectivity' => '5G, Wi-Fi',
                    'warranty' => '1 Year Official Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 2
            [
                'sku' => 'SKU-S24-256-GRY',
                'barcode' => '8851000000028',
                'name' => 'Samsung Galaxy S24 256GB Gray',
                'slug' => Str::slug('Samsung Galaxy S24 256GB Gray'),
                'short_description' => 'สมาร์ทโฟนเรือธง Android จอ AMOLED 120Hz พร้อมฟีเจอร์ AI ช่วยถ่ายภาพและใช้งานประจำวันได้ฉลาดขึ้น',
                'description' => 'Samsung Galaxy S24 ความจุ 256GB สีเทา โดดเด่นด้วยหน้าจอ Dynamic AMOLED 2X ให้สีสดและคมชัด รองรับอัตรารีเฟรช 120Hz เพื่อการเลื่อนหน้าจอลื่นไหล เหมาะกับการเล่นเกมและดูคอนเทนต์ กล้องหลัก 50MP พร้อมการประมวลผลภาพด้วย AI ช่วยให้ภาพกลางคืนและภาพบุคคลดูดีขึ้น รองรับ 5G และการเชื่อมต่อที่ทันสมัย ชาร์จเร็วและระบบจัดการพลังงานที่ดี เหมาะสำหรับคนที่ต้องการมือถือประสิทธิภาพสูงและชอบความยืดหยุ่นของ Android',
                'category_name' => 'Smartphone',
                'brand_name' => 'Samsung',
                'tags' => json_encode(['android', '5G', 'amoled', '120hz', 'ai']),
                'price' => 28900,
                'compare_at_price' => 31900,
                'cost' => 24000,
                'tax_rate' => 7.00,
                'discount_type' => 'fixed',
                'discount_value' => 1000,
                'stock_qty' => 30,
                'reserved_qty' => 3,
                'reorder_point' => 8,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.168,
                'length_cm' => 14.65,
                'width_cm' => 7.05,
                'height_cm' => 0.79,
                'shipping_class' => 'standard',
                'cover_image_url' => '/images/products/galaxy_s24_gray_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/galaxy_s24_gray_1.jpg',
                    '/images/products/galaxy_s24_gray_2.jpg',
                    '/images/products/galaxy_s24_gray_3.jpg',
                ]),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => now(),
                'meta_title' => 'Samsung Galaxy S24 256GB Gray | จอ 120Hz',
                'meta_description' => 'Galaxy S24 256GB สีเทา จอ AMOLED 120Hz กล้อง 50MP รองรับ 5G',
                'meta_keywords' => 'galaxy s24, samsung, android, amoled, 5g',
                'notes' => 'เหมาะทำสินค้าขายร่วมกับอุปกรณ์เสริม',
                'attributes' => json_encode([
                    'color' => 'Gray',
                    'storage' => '256GB',
                    'display' => 'AMOLED 120Hz',
                    'camera' => '50MP main',
                    'charging' => 'Fast charge',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 3
            [
                'sku' => 'SKU-IPAD-AIR5-64-BLU',
                'barcode' => '8851000000035',
                'name' => 'Apple iPad Air 5 64GB Blue',
                'slug' => Str::slug('Apple iPad Air 5 64GB Blue'),
                'short_description' => 'แท็บเล็ตจอ 10.9 นิ้ว น้ำหนักเบา ประสิทธิภาพสูง เหมาะเรียน ทำงาน จดโน้ต และใช้คู่กับอุปกรณ์เสริมได้ดี',
                'description' => 'iPad Air 5 ความจุ 64GB สีฟ้า เหมาะสำหรับผู้ที่ต้องการแท็บเล็ตที่พกพาง่ายแต่ประสิทธิภาพยังแรงเพียงพอสำหรับงานเรียนและงานเอกสาร หน้าจอ 10.9 นิ้วให้พื้นที่ใช้งานกำลังดี รองรับการจดโน้ต วาดรูป และทำงานหลายอย่างพร้อมกันได้สะดวก ใช้งานร่วมกับคีย์บอร์ดและปากกาได้ เหมาะทั้งนักเรียน นักศึกษา และคนทำงานที่ต้องการอุปกรณ์พกพาที่ใช้งานได้หลากหลาย',
                'category_name' => 'Tablet',
                'brand_name' => 'Apple',
                'tags' => json_encode(['tablet', 'apple', 'เรียน', 'ทำงาน', 'พกพา']),
                'price' => 21900,
                'compare_at_price' => 23900,
                'cost' => 18000,
                'tax_rate' => 7.00,
                'discount_type' => 'percent',
                'discount_value' => 5,
                'stock_qty' => 18,
                'reserved_qty' => 2,
                'reorder_point' => 6,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.461,
                'length_cm' => 24.7,
                'width_cm' => 17.8,
                'height_cm' => 0.61,
                'shipping_class' => 'large',
                'cover_image_url' => '/images/products/ipad_air5_blue_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/ipad_air5_blue_1.jpg',
                    '/images/products/ipad_air5_blue_2.jpg',
                ]),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => now(),
                'meta_title' => 'iPad Air 5 64GB Blue | เหมาะเรียนและทำงาน',
                'meta_description' => 'iPad Air 5 64GB สีฟ้า จอ 10.9 นิ้ว เบาแรง ใช้งานได้หลากหลาย',
                'meta_keywords' => 'ipad air, apple tablet, tablet for work',
                'notes' => 'จัดเป็น bundle คู่ Apple Pencil ได้',
                'attributes' => json_encode([
                    'color' => 'Blue',
                    'storage' => '64GB',
                    'display' => '10.9-inch',
                    'connectivity' => 'Wi-Fi',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 4
            [
                'sku' => 'SKU-SONY-WH1000XM5-BLK',
                'barcode' => '8851000000042',
                'name' => 'Sony WH-1000XM5 Noise Cancelling Headphones Black',
                'slug' => Str::slug('Sony WH-1000XM5 Noise Cancelling Headphones Black'),
                'short_description' => 'หูฟังครอบหูระดับพรีเมียม ตัดเสียงรบกวนยอดนิยม เหมาะทำงาน เดินทาง และฟังเพลงจริงจัง',
                'description' => 'Sony WH-1000XM5 เป็นหูฟังไร้สายแบบครอบหูที่เด่นเรื่องระบบตัดเสียงรบกวน ช่วยลดเสียงสภาพแวดล้อมได้อย่างมีประสิทธิภาพ เหมาะสำหรับการทำงานในที่สาธารณะหรือการเดินทางไกล ให้โทนเสียงที่บาลานซ์ ฟังได้นานไม่ล้า รองรับการเชื่อมต่อ Bluetooth และใช้งานกับอุปกรณ์ได้หลากหลาย แบตเตอรี่ใช้งานต่อเนื่องได้ยาว เหมาะสำหรับผู้ที่ต้องการคุณภาพเสียงและความเงียบเพื่อโฟกัส',
                'category_name' => 'Audio',
                'brand_name' => 'Sony',
                'tags' => json_encode(['headphone', 'noise cancelling', 'bluetooth', 'พรีเมียม']),
                'price' => 12900,
                'compare_at_price' => 13900,
                'cost' => 9500,
                'tax_rate' => 7.00,
                'discount_type' => 'fixed',
                'discount_value' => 700,
                'stock_qty' => 22,
                'reserved_qty' => 1,
                'reorder_point' => 6,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.250,
                'length_cm' => 20.0,
                'width_cm' => 18.0,
                'height_cm' => 8.0,
                'shipping_class' => 'standard',
                'cover_image_url' => '/images/products/sony_wh1000xm5_black_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/sony_wh1000xm5_black_1.jpg',
                    '/images/products/sony_wh1000xm5_black_2.jpg',
                ]),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => now(),
                'meta_title' => 'Sony WH-1000XM5 | หูฟังตัดเสียงรบกวน',
                'meta_description' => 'หูฟัง Sony WH-1000XM5 ตัดเสียงรบกวน คุณภาพเสียงระดับพรีเมียม',
                'meta_keywords' => 'sony wh-1000xm5, noise cancelling, headphone',
                'notes' => 'เหมาะเป็นสินค้าชูโรงหมวด Audio',
                'attributes' => json_encode([
                    'color' => 'Black',
                    'type' => 'Over-ear',
                    'connectivity' => 'Bluetooth',
                    'feature' => 'Active Noise Cancelling',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 5
            [
                'sku' => 'SKU-DELL-XPS13-I7-16-512',
                'barcode' => '8851000000059',
                'name' => 'Dell XPS 13 13.4" Intel Core i7 RAM 16GB SSD 512GB',
                'slug' => Str::slug('Dell XPS 13 Intel Core i7 RAM 16GB SSD 512GB'),
                'short_description' => 'โน้ตบุ๊กบางเบา จอ InfinityEdge เหมาะทำงานเอกสาร ประชุมออนไลน์ และพกพาใช้งานนอกสถานที่',
                'description' => 'Dell XPS 13 เป็นโน้ตบุ๊กที่เน้นงานพรีเมียม ดีไซน์บางเบาและวัสดุแข็งแรง เหมาะสำหรับสายทำงานที่ต้องพกเครื่องไปประชุมหรือทำงานนอกสถานที่ หน้าจอ InfinityEdge ช่วยให้ขอบจอบาง ดูคอนเทนต์เต็มตา ใช้ซีพียู Intel Core i7 ร่วมกับ RAM 16GB และ SSD 512GB ทำให้เปิดโปรแกรมหลายตัวพร้อมกันได้ดี การบูตและเปิดไฟล์รวดเร็ว เหมาะกับงานเอกสาร งานพรีเซนต์ งานเขียนโค้ดระดับทั่วไป และทำงานร่วมกับอุปกรณ์ผ่านพอร์ตความเร็วสูง',
                'category_name' => 'Laptop',
                'brand_name' => 'Dell',
                'tags' => json_encode(['laptop', 'ultrabook', 'work', 'business']),
                'price' => 45900,
                'compare_at_price' => 48900,
                'cost' => 40000,
                'tax_rate' => 7.00,
                'discount_type' => 'fixed',
                'discount_value' => 2000,
                'stock_qty' => 12,
                'reserved_qty' => 1,
                'reorder_point' => 3,
                'stock_status' => 'in_stock',
                'weight_kg' => 1.200,
                'length_cm' => 29.5,
                'width_cm' => 19.9,
                'height_cm' => 1.48,
                'shipping_class' => 'large',
                'cover_image_url' => '/images/products/dell_xps13_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/dell_xps13_1.jpg',
                    '/images/products/dell_xps13_2.jpg',
                    '/images/products/dell_xps13_3.jpg',
                ]),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => now(),
                'meta_title' => 'Dell XPS 13 i7/16GB/512GB | โน้ตบุ๊กพรีเมียม',
                'meta_description' => 'Dell XPS 13 ซีพียู i7 RAM 16GB SSD 512GB เหมาะทำงานและพกพา',
                'meta_keywords' => 'dell xps 13, ultrabook, laptop for work',
                'notes' => 'เหมาะทำโปรโมชันร่วม Office หรืออุปกรณ์เสริม',
                'attributes' => json_encode([
                    'cpu' => 'Intel Core i7',
                    'ram' => '16GB',
                    'storage' => '512GB SSD',
                    'display' => '13.4-inch',
                    'os' => 'Windows 11',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 6
            [
                'sku' => 'SKU-LOGI-MXMASTER-3S',
                'barcode' => '8851000000066',
                'name' => 'Logitech MX Master 3S Wireless Mouse Graphite',
                'slug' => Str::slug('Logitech MX Master 3S Wireless Mouse Graphite'),
                'short_description' => 'เมาส์ไร้สายสำหรับงานโปร ทำงานเอกสาร ตัดต่อ และใช้งานหลายหน้าจอได้สะดวก จับถนัดมือ',
                'description' => 'Logitech MX Master 3S เป็นเมาส์ไร้สายที่ออกแบบมาสำหรับผู้ทำงานจริงจัง จุดเด่นคือการจับที่สบายมือ การเลื่อนที่นุ่มและแม่นยำ เหมาะสำหรับงานเอกสาร งานออกแบบ และงานตัดต่อบางประเภท รองรับการใช้งานกับหลายอุปกรณ์ สามารถสลับการเชื่อมต่อได้ ช่วยเพิ่มประสิทธิภาพการทำงานในชีวิตประจำวัน ใช้งานได้ยาวนานต่อการชาร์จหนึ่งครั้ง เหมาะกับคนที่ต้องการเมาส์คุณภาพสูงสำหรับทำงานทุกวัน',
                'category_name' => 'Accessory',
                'brand_name' => 'Logitech',
                'tags' => json_encode(['mouse', 'wireless', 'work', 'productivity']),
                'price' => 3990,
                'compare_at_price' => 4290,
                'cost' => 2800,
                'tax_rate' => 7.00,
                'discount_type' => 'none',
                'discount_value' => null,
                'stock_qty' => 45,
                'reserved_qty' => 2,
                'reorder_point' => 12,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.141,
                'length_cm' => 12.4,
                'width_cm' => 8.4,
                'height_cm' => 5.1,
                'shipping_class' => 'small',
                'cover_image_url' => '/images/products/logitech_mxmaster3s_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/logitech_mxmaster3s_1.jpg',
                    '/images/products/logitech_mxmaster3s_2.jpg',
                ]),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => now(),
                'meta_title' => 'Logitech MX Master 3S | เมาส์ไร้สายสำหรับงานโปร',
                'meta_description' => 'เมาส์ Logitech MX Master 3S จับถนัดมือ เลื่อนนุ่ม เหมาะงานทำงานจริงจัง',
                'meta_keywords' => 'logitech mx master 3s, wireless mouse, productivity',
                'notes' => 'สินค้าขายร่วมกับโน้ตบุ๊กและคีย์บอร์ดได้ดี',
                'attributes' => json_encode([
                    'color' => 'Graphite',
                    'dpi' => 'Up to 8000',
                    'connection' => 'Bluetooth/Receiver',
                    'battery' => 'Long-lasting',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7
            [
                'sku' => 'SKU-RAZER-BW-V4',
                'barcode' => '8851000000073',
                'name' => 'Razer BlackWidow V4 Mechanical Keyboard RGB',
                'slug' => Str::slug('Razer BlackWidow V4 Mechanical Keyboard RGB'),
                'short_description' => 'คีย์บอร์ด Mechanical สำหรับเกมมิ่งและพิมพ์งาน ฟีลลิ่งชัดเจน ไฟ RGB ปรับได้ เหมาะทั้งสายเล่นเกมและสายคีย์บอร์ด',
                'description' => 'Razer BlackWidow V4 เป็นคีย์บอร์ด Mechanical ที่เน้นความทนทานและประสบการณ์การกดที่ชัดเจน เหมาะกับผู้ใช้งานที่ต้องการความแม่นยำในการเล่นเกม รวมถึงคนที่พิมพ์งานเป็นเวลานาน มีไฟ RGB ที่ปรับแต่งเอฟเฟกต์ได้ตามต้องการ ช่วยเพิ่มบรรยากาศบนโต๊ะทำงานหรือโต๊ะเกมมิ่ง โครงสร้างแข็งแรง เหมาะสำหรับการใช้งานต่อเนื่องและการตั้งค่ามาโครเพื่อเพิ่มความเร็วในการทำงาน',
                'category_name' => 'Accessory',
                'brand_name' => 'Razer',
                'tags' => json_encode(['keyboard', 'gaming', 'mechanical', 'rgb']),
                'price' => 5990,
                'compare_at_price' => 6490,
                'cost' => 4200,
                'tax_rate' => 7.00,
                'discount_type' => 'percent',
                'discount_value' => 8,
                'stock_qty' => 28,
                'reserved_qty' => 2,
                'reorder_point' => 7,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.950,
                'length_cm' => 45.0,
                'width_cm' => 15.0,
                'height_cm' => 4.0,
                'shipping_class' => 'standard',
                'cover_image_url' => '/images/products/razer_blackwidow_v4_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/razer_blackwidow_v4_1.jpg',
                    '/images/products/razer_blackwidow_v4_2.jpg',
                ]),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => now(),
                'meta_title' => 'Razer BlackWidow V4 | คีย์บอร์ด Mechanical RGB',
                'meta_description' => 'คีย์บอร์ด Razer BlackWidow V4 ไฟ RGB ฟีลกดชัด เหมาะเล่นเกมและพิมพ์งาน',
                'meta_keywords' => 'razer blackwidow v4, mechanical keyboard, gaming keyboard',
                'notes' => 'แนะนำจัดชุดคู่เมาส์เกมมิ่ง',
                'attributes' => json_encode([
                    'switch' => 'Mechanical',
                    'layout' => 'Full-size',
                    'lighting' => 'RGB',
                    'connection' => 'Wired',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 8
            [
                'sku' => 'SKU-LG-OLED-55C',
                'barcode' => '8851000000080',
                'name' => 'LG OLED TV 55" 4K Smart TV (WebOS)',
                'slug' => Str::slug('LG OLED TV 55 4K Smart TV WebOS'),
                'short_description' => 'ทีวี OLED 55 นิ้ว 4K ให้สีดำลึก คอนทราสต์สูง เหมาะดูหนัง เล่นเกม และใช้งาน Smart TV ได้ครบ',
                'description' => 'LG OLED TV ขนาด 55 นิ้ว ความละเอียด 4K โดดเด่นด้วยพาเนล OLED ที่ให้สีดำลึกและคอนทราสต์สูง ทำให้ภาพดูมีมิติ เหมาะกับการดูภาพยนตร์ ซีรีส์ และคอนเทนต์คุณภาพสูง รองรับระบบ Smart TV ผ่าน WebOS ใช้งานแอปสตรีมมิ่งได้สะดวก มีโหมดภาพและเสียงที่ปรับได้หลายรูปแบบ เหมาะทั้งใช้งานในห้องนั่งเล่นและห้องดูหนังในบ้าน รวมถึงรองรับการเชื่อมต่ออุปกรณ์ได้หลากหลาย',
                'category_name' => 'TV',
                'brand_name' => 'LG',
                'tags' => json_encode(['tv', 'oled', '4k', 'smart tv', 'cinema']),
                'price' => 39900,
                'compare_at_price' => 42900,
                'cost' => 33000,
                'tax_rate' => 7.00,
                'discount_type' => 'fixed',
                'discount_value' => 3000,
                'stock_qty' => 6,
                'reserved_qty' => 1,
                'reorder_point' => 2,
                'stock_status' => 'in_stock',
                'weight_kg' => 15.000,
                'length_cm' => 123.0,
                'width_cm' => 71.0,
                'height_cm' => 5.0,
                'shipping_class' => 'large',
                'cover_image_url' => '/images/products/lg_oled_55_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/lg_oled_55_1.jpg',
                    '/images/products/lg_oled_55_2.jpg',
                    '/images/products/lg_oled_55_3.jpg',
                ]),
                'status' => 'active',
                'is_featured' => true,
                'published_at' => now(),
                'meta_title' => 'LG OLED TV 55" 4K Smart TV | ภาพสวยสีดำลึก',
                'meta_description' => 'LG OLED 55 นิ้ว 4K Smart TV ภาพคม สีดำลึก เหมาะดูหนังและเล่นเกม',
                'meta_keywords' => 'lg oled, oled tv 55, 4k smart tv',
                'notes' => 'เหมาะทำโปรร่วมซาวด์บาร์',
                'attributes' => json_encode([
                    'size' => '55-inch',
                    'resolution' => '4K',
                    'panel' => 'OLED',
                    'os' => 'WebOS',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 9
            [
                'sku' => 'SKU-SONY-A7IV-BODY',
                'barcode' => '8851000000097',
                'name' => 'Sony A7 IV Mirrorless Camera Body',
                'slug' => Str::slug('Sony A7 IV Mirrorless Camera Body'),
                'short_description' => 'กล้อง Mirrorless Full Frame เหมาะถ่ายภาพนิ่งและวิดีโอ งานโปรดักชันและคอนเทนต์ครีเอเตอร์',
                'description' => 'Sony A7 IV กล้อง Mirrorless Full Frame ที่เน้นความสมดุลระหว่างภาพนิ่งและวิดีโอ เซนเซอร์ความละเอียดสูงช่วยให้ได้รายละเอียดคมชัด เหมาะกับงานถ่ายภาพบุคคล สินค้า และงานอีเวนต์ รองรับการถ่ายวิดีโอความละเอียดสูงสำหรับงานคอนเทนต์และงานโปรดักชัน ระบบโฟกัสทำงานรวดเร็ว เหมาะกับการจับวัตถุที่เคลื่อนไหว มีตัวเลือกเลนส์และอุปกรณ์เสริมหลากหลาย เป็นตัวเลือกยอดนิยมสำหรับผู้ที่ต้องการคุณภาพระดับมืออาชีพ',
                'category_name' => 'Camera',
                'brand_name' => 'Sony',
                'tags' => json_encode(['camera', 'mirrorless', 'full frame', 'creator', '4k']),
                'price' => 79900,
                'compare_at_price' => 82900,
                'cost' => 70000,
                'tax_rate' => 7.00,
                'discount_type' => 'none',
                'discount_value' => null,
                'stock_qty' => 7,
                'reserved_qty' => 0,
                'reorder_point' => 2,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.650,
                'length_cm' => 13.0,
                'width_cm' => 9.0,
                'height_cm' => 8.0,
                'shipping_class' => 'standard',
                'cover_image_url' => '/images/products/sony_a7iv_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/sony_a7iv_1.jpg',
                    '/images/products/sony_a7iv_2.jpg',
                ]),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => now(),
                'meta_title' => 'Sony A7 IV | กล้อง Full Frame สำหรับครีเอเตอร์',
                'meta_description' => 'Sony A7 IV กล้อง Mirrorless Full Frame เหมาะทั้งภาพนิ่งและวิดีโอ',
                'meta_keywords' => 'sony a7 iv, mirrorless, full frame camera',
                'notes' => 'แนะนำทำ bundle คู่เลนส์ยอดนิยม',
                'attributes' => json_encode([
                    'sensor' => 'Full Frame',
                    'type' => 'Mirrorless',
                    'use_case' => 'Photo & Video',
                    'mount' => 'E-mount',
                    'warranty' => '1 Year Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 10
            [
                'sku' => 'SKU-SSD-SAM-980PRO-1TB',
                'barcode' => '8851000000103',
                'name' => 'Samsung 980 PRO NVMe SSD 1TB PCIe Gen4',
                'slug' => Str::slug('Samsung 980 PRO NVMe SSD 1TB PCIe Gen4'),
                'short_description' => 'SSD NVMe ความเร็วสูง เหมาะอัปเกรดพีซี/โน้ตบุ๊ก ลดเวลาโหลดเกมและงานตัดต่อไฟล์ใหญ่',
                'description' => 'Samsung 980 PRO NVMe SSD ความจุ 1TB รองรับ PCIe Gen4 ให้ความเร็วอ่าน/เขียนสูง เหมาะสำหรับการอัปเกรดเครื่องคอมพิวเตอร์เพื่อเพิ่มความเร็วในการเปิดโปรแกรม โหลดเกม และทำงานกับไฟล์ขนาดใหญ่ เช่น งานตัดต่อวิดีโอและงานกราฟิก ช่วยลดเวลารอคอยและเพิ่มความลื่นไหลของระบบ เหมาะทั้งสายเกมมิ่ง สายทำงาน และผู้ใช้ที่ต้องการประสิทธิภาพสูงในการใช้งานประจำวัน',
                'category_name' => 'Storage',
                'brand_name' => 'Samsung',
                'tags' => json_encode(['ssd', 'nvme', 'pcie gen4', 'upgrade', 'gaming']),
                'price' => 4590,
                'compare_at_price' => 4990,
                'cost' => 3200,
                'tax_rate' => 7.00,
                'discount_type' => 'percent',
                'discount_value' => 5,
                'stock_qty' => 60,
                'reserved_qty' => 4,
                'reorder_point' => 15,
                'stock_status' => 'in_stock',
                'weight_kg' => 0.020,
                'length_cm' => 8.0,
                'width_cm' => 2.2,
                'height_cm' => 0.3,
                'shipping_class' => 'small',
                'cover_image_url' => '/images/products/samsung_980pro_1tb_main.jpg',
                'gallery_images' => json_encode([
                    '/images/products/samsung_980pro_1tb_1.jpg',
                    '/images/products/samsung_980pro_1tb_2.jpg',
                ]),
                'status' => 'active',
                'is_featured' => false,
                'published_at' => now(),
                'meta_title' => 'Samsung 980 PRO 1TB NVMe SSD | PCIe Gen4',
                'meta_description' => 'SSD NVMe Samsung 980 PRO 1TB ความเร็วสูง เหมาะอัปเกรดคอมพิวเตอร์และเล่นเกม',
                'meta_keywords' => 'samsung 980 pro, nvme ssd, pcie gen4, 1tb ssd',
                'notes' => 'เหมาะทำโปรร่วมกับเมนบอร์ด/โน้ตบุ๊ก',
                'attributes' => json_encode([
                    'capacity' => '1TB',
                    'interface' => 'NVMe PCIe Gen4',
                    'form_factor' => 'M.2 2280',
                    'use_case' => 'Gaming/Workstation',
                    'warranty' => '5 Years Limited Warranty',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}